version: "1.0"

services:
  api:
    container_name: fitnes-app-api
    image: fitnes-app-api
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /usr/src/app
    command: >
      /bin/sh -c "
        npm run start:dev
      "
    env_file: .env
    init: true
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '${PORT}:${PORT}'